package org.example.datamanagementpatterns.eventsourcingpattern.model;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Setter
@Getter
@Entity
@NoArgsConstructor // No-args constructor for JPA
@AllArgsConstructor // All-args constructor generated by Lombok
public class Event {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    private String eventType;
    private String eventPayload;

    // Lombok generates the getter, setter, no-args and all-args constructors automatically
    // You can remove the custom constructor if Lombok is generating it automatically

    // Optional: You can add custom methods or logic if needed
    // For example, a method to validate the event or format the payload
    public boolean isValid() {
        // Example of simple validation: make sure eventType and eventPayload are not null
        return eventType != null && eventPayload != null && !eventPayload.isEmpty();
    }

    // Custom logic can be added here for additional functionality if necessary.
}
